//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksserptotalweb_api.Capas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_Detalle_Impuestos
    {
        public long id_Facturas_Detalle_Impuestos { get; set; }
        public short id_TiposImpuestos { get; set; }
        public long id_Facturas_Detalle { get; set; }
        public decimal Tasa { get; set; }
    
        public virtual Facturas_Detalle Facturas_Detalle { get; set; }
    }
}
