//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksserptotalweb_api.Capas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Facturas_Detalle = new HashSet<Facturas_Detalle>();
            this.Facturas_TiposPago = new HashSet<Facturas_TiposPago>();
        }
    
        public long id_Facturas { get; set; }
        public Nullable<short> id_Cajas { get; set; }
        public Nullable<short> id_Usuarios { get; set; }
        public Nullable<long> id_Clientes { get; set; }
        public Nullable<long> id_Cajas_Cortes { get; set; }
        public Nullable<short> id_DefStatusFactura { get; set; }
        public long id_Estaciones_Sesiones { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime FechaActual { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string nroFactura { get; set; }
        public string nroFacturaIF { get; set; }
        public string nroControl { get; set; }
    
        public virtual Cajas Cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Detalle> Facturas_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_TiposPago> Facturas_TiposPago { get; set; }
    }
}
