//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksserptotalweb_api.Capas.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class kss_dbEntities : DbContext
    {
        public kss_dbEntities()
            : base("name=kss_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cajas> Cajas { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Estaciones> Estaciones { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Facturas_Detalle> Facturas_Detalle { get; set; }
        public virtual DbSet<Facturas_Detalle_Descuentos> Facturas_Detalle_Descuentos { get; set; }
        public virtual DbSet<Facturas_Detalle_Impuestos> Facturas_Detalle_Impuestos { get; set; }
        public virtual DbSet<Facturas_TiposPago> Facturas_TiposPago { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Productos_Familias> Productos_Familias { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<TiposUnidadesMedida> TiposUnidadesMedida { get; set; }
    
        public virtual int deleteProductos_idProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteProductos_idProducto", idProductoParameter);
        }
    
        public virtual ObjectResult<getProductos_Result> getProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductos_Result>("getProductos");
        }
    
        public virtual ObjectResult<getProductos_idProducto_Result> getProductos_idProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductos_idProducto_Result>("getProductos_idProducto", idProductoParameter);
        }
    }
}
