//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksserptotalweb_api.Capas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursales
    {
        public long id_sucursales { get; set; }
        public long id_empresas { get; set; }
        public Nullable<long> id_world_Localidades { get; set; }
        public long id_world_Regiones { get; set; }
        public Nullable<long> id_world_Idiomas { get; set; }
        public Nullable<short> id_ven_Municipios { get; set; }
        public Nullable<long> id_world_Paises { get; set; }
        public Nullable<long> id_ven_Parroquias { get; set; }
        public long id_tiposComercio { get; set; }
        public string codigoPostal { get; set; }
        public string Contacto { get; set; }
        public string direccion { get; set; }
        public string empresa { get; set; }
        public Nullable<bool> esActivo { get; set; }
        public string ImagenArchivo { get; set; }
        public string nit { get; set; }
        public string rif { get; set; }
        public string telefonos { get; set; }
        public string telefonosContacto { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
